### ISSUE TITLE
Add concurrency to (at least) all auto-generate-docs workflows for all reps

### ISSUE THREAD

**Issue by sebastian-sommerfeld-io** [sebastian-sommerfeld-io/configs#79]
```yaml
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
```
